;;@@@@@@@@@@@@@@@@@@@@
;;repositories for future packages
;;@@@@@@@@@@@@@@@@@@@@
(require 'package) ;;will not work without these packages

(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/")
	     t)

(package-initialize)

;;@@@@@@@@@@@@@@@@@@@@
;;makes sure that the package is installed - it ensures that you can dynamically load packages from the config file on any computer
;;@@@@@@@@@@@@@@@@@@@@
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;;@@@@@@@@@@@@@@@@@@@@
;;load commands from the org file
;;@@@@@@@@@@@@@@@@@@@@
(setq load-prefer-newer t)		;avoid el newer than files error
(org-babel-load-file (expand-file-name "~/creamy_seas/sync_files/emacs_config/config.org"))

;;@@@@@@@@@@@@@@@@@@@@
;;generated by emacs
;;@@@@@@@@@@@@@@@@@@@@
