;;@@@@@@@@@@@@@@@@@@@@
;;repositories for future packages
;;@@@@@@@@@@@@@@@@@@@@
(require 'package) ;;will not work without these packages

(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/")
	     t)

(package-initialize)

;;@@@@@@@@@@@@@@@@@@@@
;;makes sure that the package is installed - it ensures that you can dynamically load packages from the config file on any computer
;;@@@@@@@@@@@@@@@@@@@@
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;;@@@@@@@@@@@@@@@@@@@@
;;load commands from the org file
;;@@@@@@@@@@@@@@@@@@@@
(org-babel-load-file (expand-file-name "~/creamy_seas/syncFiles/emacs_config/config.org"))

;;@@@@@@@@@@@@@@@@@@@@
;;generated by emacs
;;@@@@@@@@@@@@@@@@@@@@
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (hideshow-org smart-mode-line-powerline-theme sml smart-mode-line webkit-color-picker helm-colors magit org-ac markdown-mode iedit exec-path-from-shell fill-column-indicator auto-complete-auctex preview-latex cdlatex pyenv-mode jedi htmlize org-reveal flycheck counsel ox-reveal elfeed-web hydra elfeed-goodies elfeed-org try yasnippet-snippets company-irony captain expand-region mark-multiple linum-relative popup-kill-ring swiper epa-file symon dmenu diminish spaceline company dashboard rainbow-delimiters sudo-edit hungry-delete avy ido-vertical-mode beacon f org-bullets spacemacs-theme which-key use-package auctex yasnippet w3 undo-tree switch-window smex ranger powerline nlinum-relative multiple-cursors minimap autopair auto-complete alpha ace-jump-mode))))
