#!/bin/bash


#----------------------------------------
# JEW ENGINE
#----------------------------------------
# Using the direcotry that clean was launched from 
# 1) determine if we are in the master directory of the latex project
# 2) move any files generated by latex into the "_output" folder in the master directory
# 3) copy over the master pdf and tex files back - we want to keep those!
#
# $1 name of the master file (%s in auctex)
#----------------------------------------

#1) remove and copy the generate "_output" directory in the master directory
rm -r ./auto 2> /dev/null
mkdir -p ./_output 2> /dev/null

#2) copy all the files into there and move pdf and tex back
sleep 1
mv -f "./$1."* ./_output 2> /dev/null
mv "./_output/$1."{pdf,tex} . 2> /dev/null
