#!/bin/bash


#----------------------------------------
# JEW ENGINE
#----------------------------------------
# Using the direcotry that clean was launched from 
# 1) determine if we are in the master directory of the latex project
# 2) move any files generated by latex into the "_output" folder in the master directory
# 3) copy over the master pdf and tex files back - we want to keep those!
#
# $1 name of the master file (%s in auctex)
#----------------------------------------

#1) check if the master file is in this directory
if [ -f $1 ]; then
    #2) if the master file is in this directory, all operations done locally
    relMastDir="."
else
    #3) if there is no master file, all operations are done on the parent directory
    relMastDir="."
fi

#4) remove and copy the generate "_output" directory in the master directory
rm -r $relMastDir/auto 2> /dev/null
mkdir -p $relMastDir/_output

#5) copy all the files into there and move pdf and tex back
mv $relMastDir/$1.* $relMastDir/_output
mv $relMastDir/_output/$1.{pdf,tex} $relMastDir
